admins/urls.py
from django.urls import path
from .views import *

app_name = 'admins'

urlpatterns = [
    path('',home),
    path('dashboard/',DashboardView.as_view(),name='dashboard'),
    path('staff/',StaffListView.as_view(),name="staff"),
    path('staff/add/',StaffAddFormView.as_view(),name="staff-add"),
    path('staff/<int:pk>/',StaffDetailView.as_view(),name="staff-details"),
    path('staff/<int:id>/get-schedule/',scheduleGetView),
    path('staff/<int:id>/toggle-status/',StaffStatusToggle.as_view(),name="staff-toggle"),
    path('staff/<int:id>/delete/',StaffDeleteView.as_view(),name="staff-delete"),
    path('student/',StudentListView.as_view(),name="student"),
    path('student/add/',StudentAddFormView.as_view(),name="student-add-form"),
    path('student/<int:pk>/',StudentDetailView.as_view(),name="student-details"),
    path('student/<int:id>/toggle-status/',StudentStatusToggle.as_view(),name="student-toggle"),
    path('student/<int:id>/delete/',StudentDeleteView.as_view(),name="student-delete"),
    path('mail/',InboxView.as_view(),name="inbox"),
    path('mail/received/',InboxReceivedView.as_view(),name="inbox-received"),
    path('mail/sent/',InboxSentView.as_view(),name="inbox-sent"),
    path('mail/create/',InboxFormView.as_view(),name="inbox-create"),
    path('event/',EventView.as_view(),name="event"),
    path('event/add/',EventFormView.as_view(),name="event-add"),
    path('event/<int:id>/',EventDetailsView.as_view(),name="event"),
    path('programme/',ProgrammeView.as_view(),name="programme"),
    path('programme/add-class',ProgrammeClassFormView.as_view(),name="programme-add-class"),
    path('programme/add-subject',ProgrammeSubjectFormView.as_view(),name="programme-add-subject"),
    path('programme/add-topic',ProgrammeTopicFormView.as_view(),name="programme-add-topic"),
    path('programme/class/<int:pk>/edit',ProgrammeUpdateClassView.as_view(),name="programme-edit-class"),
    path('programme/subject/<int:pk>/edit',ProgrammeUpdateSubjectView.as_view(),name="programme-edit-subject"),
    path('settings/',SettingsView.as_view(),name="settings"),
    path('settings/password',SettingsPasswordChangeView.as_view(),name="settings-password"),
    path('logout/',LogoutView.as_view(),name="logout"),
]

main/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('',indexview,name = 'index'),
    path('about/',aboutview,name = 'about'),
    path('contact-us/',contactview,name = 'contact'),
    path('news',newsview,name = 'news'),
    path('news/<int:id>/',newsdetailview,name = 'news-detail'),
    path('login/',LoginView.as_view(),name = 'login')
]

schoolportal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import main
import staff
import admins
urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('',include("main.urls")),
    path('admin/',include("admins.urls")),
    path('staff/',include("staff.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.home,name = "home"),
    path('dashboard/', views.DashboardView.as_view(),name = "dashboard"),
    path('dashboard/get-schedule/', views.scheduleGetView),
    path('profile/', views.ProfileView.as_view(),name = "profile"),
    path('profile/edit/', views.EditProfileView.as_view(),name = "edit-profile"),
    path('profile/change-password/', views.UserPasswordChangeView.as_view(),name = "change-password"),
    path('classes/', views.ClassListView.as_view(),name = "class"),
    path('students/', views.StudentListView.as_view(),name = "student-list"),
    path('students/<int:id>', views.StudentDetailsView.as_view(),name = "student-details"),
    path('inbox/', views.InboxListView.as_view(),name = "inbox-list"),
    path('inbox/<int:id>', views.InboxDetailsView.as_view(),name = "inbox-details"),
    path('inbox/<int:id>/delete', views.InboxDeleteView.as_view(),name = "inbox-delete"),
    path('uploads/', views.UploadView.as_view(),name = "uploads"),
    path('logout/', views.LogoutView.as_view(),name = "logout"),
]

admins/models.py
# from distutils.command.upload import upload
# from email.mime import image
# from email.policy import default
# from secrets import choice
# from turtle import position
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# Create your models here.
def numeric_validator(value):
    if not value.isnumeric():
        raise ValidationError(_("This field should only contain numbers"))
def phone_validator(value):
    if not value.isnumeric():
        raise ValidationError(_("The phone number is not a number"))
    if len(value) != 11:
        raise ValidationError(_("The phone number should be 11 digits"))
    phone_start_number = ['081','080','090','091','070']
    if value[:3]  in phone_start_number:
        pass
    else:
        raise ValidationError(_("Enter a valid nigerian number"))

def alpha_validator(value):
    if not value.isalpha():
        raise ValidationError(_("This field should only contain alphabets"))

class BaseManager(UserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)
class User(AbstractUser):
    username = None
    email = models.EmailField(
        _('Email'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        error_messages={
            'unique': _("A user with that email already exists."),
        },
    )
    is_teacher = models.BooleanField(default=False)
    objects = BaseManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Admin(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    firstname = models.CharField(max_length=55,validators=[alpha_validator])
    lastname = models.CharField(max_length=55,validators=[alpha_validator])
    
    image = models.ImageField(upload_to = 'admin-images',blank = True)
    phonenumber = models.CharField(
        _('Phone Number'),
        max_length=11,
        validators = [phone_validator],
        help_text=_('Required. 11 Nigeria Phone Numbers.'),
        error_messages={
            'max_length': _("11 Numbers required."),
        },
        unique=True,
    )

    def __str__(self):
        return self.firstname+" "+self.lastname

class Subject(models.Model):
    name = models.CharField(max_length=100)
    abbr = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class Class(models.Model):
    name = models.CharField(max_length=100,unique=True)
    classteacher = models.CharField(max_length=50,blank = True)
    subject = models.ManyToManyField(Subject,blank=True)

    def __str__(self):
        return self.name
    def student_number(self):
        return self.student_set.all().count()

class TeacherProgramme(models.Model):
    _class = models.ForeignKey(Class, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    report = models.FileField(upload_to="programme-reports",blank = True)

    def __str__(self):
        return str(self._class.name)+" - "+str(self.subject.name)
class Staff(models.Model):
    staff_type_choices = (('t','TEACHING'),('n','NON-TEACHING'))
    user = models.OneToOneField(User,on_delete=models.CASCADE, blank = True,null = True)
    firstname = models.CharField("First Name",max_length=55,validators=[alpha_validator])
    lastname = models.CharField("Last Name",max_length=55,validators=[alpha_validator])
    dob = models.DateField("Date of Birth")
    sex = models.CharField(max_length=10,choices=(('M','Male'),('F','Female')))
    phonenumber = models.CharField(_('Phone Number'),max_length=11,validators = [phone_validator],
        help_text=_('Required. 11 Nigeria Phone Numbers.'),error_messages={
            'max_length': _("11 Numbers required."),
        },unique=True)
    state = models.CharField(max_length=20)
    lga = models.CharField("Local Government Area",max_length=50)
    hometown = models.CharField("Home Town",max_length=50)
    residential_address = models.TextField(default="Prefer not to say",blank=True,max_length=1000)
    image = models.ImageField(upload_to = "teacher-images",blank = True,null = True)
    accountnumber = models.CharField(max_length=10,validators=[numeric_validator],blank = True)
    accountname = models.CharField(max_length=255,blank = True)
    bank = models.CharField(max_length=100, blank = True)
    staff_type = models.CharField(max_length = 2,choices = staff_type_choices)
    programme = models.ManyToManyField(TeacherProgramme,blank = True)
    status = models.BooleanField(default = True)
    position = models.CharField(max_length=30)

    def __str__(self):
        return self.firstname +" "+self.lastname

class Student(models.Model):
    firstname = models.CharField("First Name",max_length=55,validators=[alpha_validator])
    lastname = models.CharField("Last Name",max_length=55,validators=[alpha_validator])
    dob = models.DateField("Date of Birth")
    sex = models.CharField(max_length=10,choices=(('M','Male'),('F','Female')))
    state = models.CharField(max_length=20)
    lga = models.CharField("Local Government Area",max_length=50)
    hometown = models.CharField("Home Town",max_length=50)
    residential_address = models.TextField(default="Prefer not to say",max_length=1000)
    image = models.ImageField(upload_to = "student-images",blank = True,null = True)
    guardianname = models.CharField("Guardian Name",max_length=55)
    guardianphonenumber = models.CharField(_('Phone Number'),max_length=11,validators = [phone_validator],
        help_text=_('Required. 11 Nigeria Phone Numbers.'),error_messages={
            'max_length': _("11 Numbers required."),
        })
    guardianemail = models.EmailField()
    _class = models.ForeignKey(Class,null = True,on_delete=models.SET_NULL)
    subjects = models.ManyToManyField(Subject,blank = True)
    classaverage = models.FloatField(blank =  True,null = True)
    classposition = models.IntegerField(blank = True,null = True)
    status = models.BooleanField(default=True)
    def __str__(self):
        return self.firstname +' '+self.lastname

class Schedule(models.Model):
    teacher = models.ForeignKey(Staff,on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    _class = models.ForeignKey(Class,on_delete=models.SET_NULL,null = True,blank = True)
    date = models.DateField()
    time = models.TimeField()

    def __str__(self):
        return self.teacher.firstname +' '+self.teacher.lastname

class Event(models.Model):
    name = models.CharField(max_length = 50)
    description = models.TextField(max_length=1500)
    date = models.DateField()
    time = models.TimeField()
    # session = models.CharField(max_length = 20)

    def __str__(self):
        return self.name
    
class EventImage(models.Model):
    event = models.ForeignKey(Event,on_delete=models.CASCADE)
    image = models.ImageField(upload_to = 'event-images')

    def __str__(self):
        return self.event.name

class Mail(models.Model):
    flag_choices = (('u','URGENT'),('i','INFO'))
    _from = models.ForeignKey(User,on_delete=models.SET_NULL,blank = True,null = True,related_name="_from")
    to = models.ForeignKey(User,blank = True,null = True,on_delete = models.SET("deleted user"))
    subject = models.CharField(max_length=100)
    message = models.TextField(max_length = 1500)
    attachment = models.FileField(upload_to = 'mail',blank = True)
    read = models.BooleanField(default = False)
    flag = models.CharField(max_length=2,choices = flag_choices)
    date = models.DateField(auto_now_add = True)
    time = models.TimeField(auto_now_add = True)

    def __str__(self):
        return self.subject

class SiteSetting(models.Model):
    name = models.CharField(max_length=20)
    value = models.CharField(max_length=50)

    def __str__(self):
        return self.name

staff/models.py
from django.db import models

# Create your models here.

staff/forms.py
from django import forms
from django.forms import ValidationError
from admins.models import Schedule, Staff,phone_validator

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        # fields = '__all__'
        exclude = ['teacher']
        widgets = {
            '_class':forms.Select(attrs={'class':'form-control'})
        }

class UploadForm(forms.Form):
    message = forms.CharField(max_length=50)
    category = forms.ChoiceField()
    file = forms.FileField()
class EditProfileForm(forms.ModelForm):
    phonenumber = forms.CharField(validators=[phone_validator])
    class Meta:
        model = Staff
        exclude = ['programme','status','position','user','phonenumber',"staff_type"]

admins/templates/admins/base.html
{% load staticfiles %}
{% load path_checker %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.0/css/bootstrap.min.css" integrity="sha512-NZ19NrT58XPK5sXqXnnvtf9T5kLXSzGQlVZL9taZWeTBtXoN3xIfTdxbkQh6QSoJfJgpojRqMfhyqBAAEeiXcA==" crossorigin="anonymous" referrerpolicy="no-referrer" /> -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;400&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
      integrity="sha512-xX2rYBFJSj86W54Fyv1de80DWBq7zYLn2z0I9bIhQG+rxIF6XVJUpdGnsNHWRa6AvP89vtFupEPDP8eZAtu9qA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="{% static 'admins/fontawesome-free-5.12.1-web/css/all.min.css' %}"
    />
    
    
    <link rel="stylesheet" href="{% static 'staff/variables.css' %}" />
    <link rel="stylesheet" href="{% static 'admins/style.css' %}" />
    {% block extrastyle %}
    
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="wrapper">
      <div class="sidebar">
        <h2 class="sidenav-header">Admin</h2>
        <ul class="nav-list">
          <li>
            <a href="{% url 'admins:dashboard' %}" class="nav-link {% if request.path|pathcheck:'/admin/dashboard/' %}nav-active{% endif %}"
              ><span class="nav-icon"><i class="fas fa-th-large"></i></span
              ><span class="nav-text">Dashboard</span></a
            >
          </li>
          <li>
            <a href="{% url 'admins:staff' %}" class="nav-link {% if request.path|pathcheck:'/admin/staff/' %}nav-active{% endif %}"
              ><span class="nav-icon"><i class="fas fa-users"></i></span
              ><span class="nav-text">Staffs</span></a
            >
          </li>
          <li>
            <a href="{% url 'admins:student' %}" class="nav-link {% if request.path|pathcheck:'/admin/student/' %}nav-active{% endif %}"
              ><span class="nav-icon"><i class="fas fa-user-graduate"></i></span
              ><span class="nav-text">Students</span></a
            >
          </li>
          <li>
            <a href="{% url 'admins:inbox' %}" class="nav-link {% if request.path|pathcheck:'/admin/mail/' %}nav-active{% endif %}"
              ><span class="nav-icon"><i class="fas fa-envelope"></i></span
              ><span class="nav-text">Inbox</span></a
            >
          </li>
          <li>
            <a href="{% url 'admins:event' %}" class="nav-link {% if request.path|pathcheck:'/admin/event/' %}nav-active{% endif %}"
              ><span class="nav-icon"><i class="fas fa-calendar-alt"></i></span
              ><span class="nav-text">Events</span></a
            >
          </li>
          <li>
            <a href="{% url 'admins:programme' %}" class="nav-link {% if request.path|pathcheck:'/admin/programme/' %}nav-active{% endif %}"
              ><span class="nav-icon"><i class="fas fa-tasks"></i></span
              ><span class="nav-text">Programme</span></a
            >
          </li>

          <li>
            <a href="{% url 'admins:settings' %}" class="nav-link {% if request.path|pathcheck:'/admin/settings/' %}nav-active{% endif %}"
              ><span class="nav-icon"><i class="fas fa-cog"></i></span
              ><span class="nav-text">Settings</span></a
            >
          </li>
          <li>
            <a href="javascript:void(0)" id="logout-open" class="nav-link"
              ><span class="nav-icon"><i class="fas fa-sign-out-alt"></i></span
              ><span class="nav-text">Sign Out</span></a
            >
          </li>
        </ul>
      </div>
      <div class="content">
        {% for message in messages %}
        <div class="flex-center w-100 pt-3 pb-3"  style="position: absolute; z-index: 1000;">
          <div class="alert alert-{{message.tags}} text-center" style=" max-width: 300px; margin: auto;" role="alert" id="liveAlert">
            {{message}}  
          </div>
        </div>
        {% endfor %}
    {% block content %}
    
    {% endblock %}
    </div>
    
    <div class="modal-box hidden" id="logout-modal">
      <div class="form-box">
        <h3 class="header">Are you Sure?</h3>
        <div class="logout-box">
          <div class="form-group flex-between">
            <a href="{% url 'admins:logout'%}" class="site-button">Logout</a>
            <a
              href="javascript::void(0)"
              id="logout-close"
              class="site-button site-button-invert"
              >Cancel</a
            >
          </div>
        </div>
      </div>
    </div>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.min.js"
      integrity="sha512-EKWWs1ZcA2ZY9lbLISPz8aGR2+L7JVYqBAYTq5AXgBkSjRSuQEGqWx8R1zAX16KdXPaCjOCaKE8MCpU0wcHlHA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <script src="{% static 'admins/sigout.js' %}"></script>
    <script src="{% static 'admins/script.js' %}"></script>
    {% block extrascript %}

    {% endblock %}
  </body>
</html>

admins/templates/admins/inbox-sent.html
{% extends 'admins/base.html' %}
{% load staticfiles %}
{% block title %} Inbox {% endblock %}
{% block extrastyle %}
<link rel="stylesheet" href="{% static 'staff/apis/smart.default.css' %}" />
{% endblock %}
{% block content %}
        <div class="content-nav">
          <h2 class="greetings">Inbox</h2>
          <!-- nav btn -->
          <div class="nav-link-add">
            <a href="{% url 'admins:inbox-sent'%}" class="nav-icon-save">Sent</a>
            <a href="{% url 'admins:inbox-received'%}" class="nav-icon-cancel">Received</a>
          </div>
          <a href="{% url 'admins:inbox-create' %}" class="content-nav-link">
            <span class="nav-icon">
              <i class="fas fa-pen-alt"></i>
            </span>
          </a>
        </div>

        <!-- content features -->

        <div class="inbox-items">
          <!-- messages -->
          <div class="messages">
            <div class="content-scroll-up">
                {% for object in page_obj %}
                <div class="content-sub-inbox">
                    <a href="#" class="content-subject-up">{{object.subject}}:</a>
    
                    <p class="content-info">{{object.message|truncatechars:24}}</p>
                    <span class="status-icon color-danger"
                      ><i class="fas fa-bookmark"></i
                    ></span>
                    <footer class="flex-end small-text">
                      <span><i class="fas fa-clock"></i>{{object.time}}</span>&nbsp;&nbsp;
                      <span
                        ><i class="fas fa-calendar-alt"></i>{{object.date}}</span
                      >
                    </footer>
                    <!-- dropdown -->
                  </div>
                {% empty %}
                <div class="no-item">
                    <p>No Mail</p>
                </div>
                {% endfor %}
                
            </div>
            {% if page_obj %}
                <div class="flex-center">
                    <ul class="paginator">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" ><span>&laquo;</span></a></li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}">{{page_obj.previous_page_number}}</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true"><span>&laquo;</span></a></li>
                        {% endif %}
                        
                        {% for pagenum in page_obj.paginator.page_range %}
                        {% if page_obj.number == pagenum %}
                            <li class="page-item{% if page_obj.number == pagenum %} active{% endif %}">
                                <a class="page-link" href="?page={{pagenum}}">{{pagenum}}</a>
                            </li>
                        {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?}page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}"><span>&raquo;</span></a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#" ><span>&raquo;</span></a></li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
          </div>
          <!-- calendar -->
          <div class="calendar">
            <smart-calendar id="calander"></smart-calendar>
          </div>
        </div>
{% endblock %}
{% block extrascript %}
<script type="module" src="{% static 'staff/apis/smart.calendar.js' %}"></script>
<script>
    window.onload = function(){
    Smart('#calendar', class {
    get properties() {
        return {"selectedDates":[new Date(),"2022-7-17"]}
    }
  });
    };
</script>
{% endblock %}

admins/templates/admins/inbox.html
{% extends 'admins/base.html' %}
{% load staticfiles %}
{% block title %} Inbox {% endblock %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'staff/apis/smart.default.css' %}" />
{% endblock %}
{% block content %}
        <div class="content-nav">
          <h2 class="greetings">Inbox</h2>
          <!-- nav btn -->
          <div class="nav-link-add">
            <a href="{% url 'admins:inbox-sent'%}" class="nav-icon-cancel">Sent</a>
            <a href="{% url 'admins:inbox-received'%}" class="nav-icon-save">Received</a>
          </div>
          <a href="{% url 'admins:inbox-create' %}" class="content-nav-link">
            <span class="nav-icon">
              <i class="fas fa-pen-alt"></i>
            </span>
          </a>
        </div>

        <!-- content features -->

        <div class="inbox-items">
          <!-- messages -->
          <div class="messages">
            <div class="content-scroll-up">
              {% for object in page_obj %}
              <div class="content-sub-inbox">
                  <a href="#" class="content-subject-up">{{object.subject}}:</a>
  
                  <p class="content-info">{{object.message|truncatechars:24}}</p>
                  <span class="status-icon color-danger"
                    ><i class="fas fa-bookmark"></i
                  ></span>
                  <footer class="flex-end small-text">
                    <span><i class="fas fa-clock"></i>{{object.time}}</span>&nbsp;&nbsp;
                    <span
                      ><i class="fas fa-calendar-alt"></i>{{object.date}}</span
                    >
                  </footer>
                  <!-- dropdown -->
                </div>
              {% empty %}
              <div class="no-item">
                  <p>No Mail</p>
              </div>
              {% endfor %}
              
          </div>
          {% if page_obj %}
              <div class="flex-center">
                  <ul class="paginator">
                      {% if page_obj.has_previous %}
                          <li class="page-item"><a class="page-link" ><span>&laquo;</span></a></li>
                          <li class="page-item">
                              <a class="page-link" href="?page={{page_obj.previous_page_number}}">{{page_obj.previous_page_number}}</a>
                          </li>
                          {% else %}
                          <li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true"><span>&laquo;</span></a></li>
                      {% endif %}
                      
                      {% for pagenum in page_obj.paginator.page_range %}
                      {% if page_obj.number == pagenum %}
                          <li class="page-item{% if page_obj.number == pagenum %} active{% endif %}">
                              <a class="page-link" href="?page={{pagenum}}">{{pagenum}}</a>
                          </li>
                      {% endif %}
                      {% endfor %}
                      {% if page_obj.has_next %}
                          <li class="page-item"><a class="page-link" href="?}page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}</a></li>
                          <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}"><span>&raquo;</span></a></li>
                      {% else %}
                          <li class="page-item disabled"><a class="page-link" href="#" ><span>&raquo;</span></a></li>
                      {% endif %}
                  </ul>
              </div>
          {% endif %}
          </div>
          <!-- calendar -->
          <div class="calendar">
            <smart-calendar id="calander"></smart-calendar>
          </div>
        </div>
{% endblock %}
{% block extrascript %}
<script type="module" src="{% static 'staff/apis/smart.calendar.js' %}"></script>
<script>
    window.onload = function(){
    Smart('#calendar', class {
    get properties() {
        return {"selectedDates":[new Date(),"2022-7-17"]}
    }
  });
    };
</script>
{% endblock %}

admins/templates/admins/programme.html
{% extends 'admins/base.html' %}
{% block title %} Programme {% endblock %}
{% block content %}
        <div class="content-nav">
          <h2 class="greetings">Programme</h2>
          <div class="nav-link-add">
            <a href="{% url 'admins:programme-add-class' %}" class="nav-icon-add">Add class</a>
            <a href="{% url 'admins:programme-add-subject' %}" class="nav-icon-add second-btn">Add Subject</a>
            <a href="{% url 'admins:programme-add-topic' %}" class="nav-icon-add second-btn">Add Topic</a>
          </div>
        </div>

        <!-- all syllabus -->
        <div class="global-syllabus">
          <div class="box table-box display">
            {% for subject in subjects%}
            <div class="subject">
              <!-- subject -->
              <a href="{% url 'admins:programme-edit-subject' subject.pk %}" class="subject-header">{{subject.abbr}}</a>
            </div>
            {% endfor %}
          </div>
        </div>

        <!-- all syllabus junior school -->
        <!-- jss1 syllabus -->
        {% for class in classes %}
        <div class="syllabus">
          <div class="syllabus-class flex-between">
            <h1>{{ class.name }}</h1>
            <a href="{% url 'admins:programme-edit-class' class.pk %}" class="site-button" style="margin-right: 20px;"><i class="fas fa-pen-alt"></i> Edit </a>
          </div>
          <!-- table data -->
          <div class="box table-box">
            <ul class="unstyle mb-4">
              <li>No. of Subjects: {{class.subject.all|length}}</li>
              <li>No of Students: {{class.student_number}}</li>
              <li>Class Teacher: {{class.classteacher}}</li>
            </ul>
            {% if class.subject.all %}
            <table class="style-table">
              <thead>
                <tr>
                  <th>Subject</th>

                  <th>Abbr</th>

                  
                </tr>
              </thead>
              <tbody>
                {% for subject in class.subject.all %}
                <tr>
                  <td>{{subject.name}}</td>
                  <td>{{subject.abbr}}</td>

                  
                </tr>
                
                {% endfor%}
                
              </tbody>
            </table>
            {% else %}
            <div class="no-item">
              <p>No Subject</p>
            </div>
            {% endif %}
            
          </div>
        </div>
        {% endfor %}
{% endblock %}