main/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('',indexview,name = 'index'),
    path('about/',aboutview,name = 'about'),
    path('contact-us/',contactview,name = 'contact'),
    path('news',newsview,name = 'news'),
    path('news/<int:id>/',newsdetailview,name = 'news-detail'),
    path('login/',LoginView.as_view(),name = 'login')
]

schoolportal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import main
import staff
import admins
urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('',include("main.urls")),
    path('admin/',include("admins.urls")),
    path('staff/',include("staff.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.home,name = "home"),
    path('dashboard/', views.DashboardView.as_view(),name = "dashboard"),
    path('dashboard/get-schedule/', views.scheduleGetView),
    path('profile/', views.ProfileView.as_view(),name = "profile"),
    path('profile/edit/', views.EditProfileView.as_view(),name = "edit-profile"),
    path('profile/change-password/', views.UserPasswordChangeView.as_view(),name = "change-password"),
    path('classes/', views.ClassListView.as_view(),name = "class"),
    path('students/', views.StudentListView.as_view(),name = "student-list"),
    path('students/<int:id>', views.StudentDetailsView.as_view(),name = "student-details"),
    path('inbox/', views.InboxListView.as_view(),name = "inbox-list"),
    path('inbox/<int:id>', views.InboxDetailsView.as_view(),name = "inbox-details"),
    path('inbox/<int:id>/delete', views.InboxDeleteView.as_view(),name = "inbox-delete"),
    path('uploads/', views.UploadView.as_view(),name = "uploads"),
    path('logout/', views.LogoutView.as_view(),name = "logout"),
]

admins/models.py
# from distutils.command.upload import upload
# from email.mime import image
# from email.policy import default
# from secrets import choice
# from turtle import position
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# Create your models here.
def numeric_validator(value):
    if not value.isnumeric():
        raise ValidationError(_("This field should only contain numbers"))
def phone_validator(value):
    if not value.isnumeric():
        raise ValidationError(_("The phone number is not a number"))
    if len(value) != 11:
        raise ValidationError(_("The phone number should be 11 digits"))
    phone_start_number = ['081','080','090','091','070']
    if value[:3]  in phone_start_number:
        pass
    else:
        raise ValidationError(_("Enter a valid nigerian number"))

def alpha_validator(value):
    if not value.isalpha():
        raise ValidationError(_("This field should only contain alphabets"))

class BaseManager(UserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)
class User(AbstractUser):
    username = None
    email = models.EmailField(
        _('Email'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        error_messages={
            'unique': _("A user with that email already exists."),
        },
    )
    is_teacher = models.BooleanField(default=False)
    objects = BaseManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Admin(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    firstname = models.CharField(max_length=55,validators=[alpha_validator])
    lastname = models.CharField(max_length=55,validators=[alpha_validator])
    
    image = models.ImageField(upload_to = 'admin-images',blank = True)
    phonenumber = models.CharField(
        _('Phone Number'),
        max_length=11,
        validators = [phone_validator],
        help_text=_('Required. 11 Nigeria Phone Numbers.'),
        error_messages={
            'max_length': _("11 Numbers required."),
        },
        unique=True,
    )

    def __str__(self):
        return self.firstname+" "+self.lastname

class Subject(models.Model):
    name = models.CharField(max_length=100)
    abbr = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class Class(models.Model):
    name = models.CharField(max_length=100,unique=True)
    classteacher = models.CharField(max_length=50,blank = True)
    subject = models.ManyToManyField(Subject,blank=True)

    def __str__(self):
        return self.name
    def student_number(self):
        return self.student_set.all().count()

class TeacherProgramme(models.Model):
    _class = models.ForeignKey(Class, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    report = models.FileField(upload_to="programme-reports",blank = True)

    def __str__(self):
        return str(self._class.name)+" - "+str(self.subject.name)
class Staff(models.Model):
    staff_type_choices = (('t','TEACHING'),('n','NON-TEACHING'))
    user = models.OneToOneField(User,on_delete=models.CASCADE, blank = True,null = True)
    firstname = models.CharField("First Name",max_length=55,validators=[alpha_validator])
    lastname = models.CharField("Last Name",max_length=55,validators=[alpha_validator])
    dob = models.DateField("Date of Birth")
    sex = models.CharField(max_length=10,choices=(('M','Male'),('F','Female')))
    phonenumber = models.CharField(_('Phone Number'),max_length=11,validators = [phone_validator],
        help_text=_('Required. 11 Nigeria Phone Numbers.'),error_messages={
            'max_length': _("11 Numbers required."),
        },unique=True)
    state = models.CharField(max_length=20)
    lga = models.CharField("Local Government Area",max_length=50)
    hometown = models.CharField("Home Town",max_length=50)
    residential_address = models.TextField(default="Prefer not to say",blank=True,max_length=1000)
    image = models.ImageField(upload_to = "teacher-images",blank = True,null = True)
    accountnumber = models.CharField(max_length=10,validators=[numeric_validator],blank = True)
    accountname = models.CharField(max_length=255,blank = True)
    bank = models.CharField(max_length=100, blank = True)
    staff_type = models.CharField(max_length = 2,choices = staff_type_choices)
    programme = models.ManyToManyField(TeacherProgramme,blank = True)
    status = models.BooleanField(default = True)
    position = models.CharField(max_length=30)

    def __str__(self):
        return self.firstname +" "+self.lastname

class Student(models.Model):
    firstname = models.CharField("First Name",max_length=55,validators=[alpha_validator])
    lastname = models.CharField("Last Name",max_length=55,validators=[alpha_validator])
    dob = models.DateField("Date of Birth")
    sex = models.CharField(max_length=10,choices=(('M','Male'),('F','Female')))
    state = models.CharField(max_length=20)
    lga = models.CharField("Local Government Area",max_length=50)
    hometown = models.CharField("Home Town",max_length=50)
    residential_address = models.TextField(default="Prefer not to say",max_length=1000)
    image = models.ImageField(upload_to = "student-images",blank = True,null = True)
    guardianname = models.CharField("Guardian Name",max_length=55)
    guardianphonenumber = models.CharField(_('Phone Number'),max_length=11,validators = [phone_validator],
        help_text=_('Required. 11 Nigeria Phone Numbers.'),error_messages={
            'max_length': _("11 Numbers required."),
        })
    guardianemail = models.EmailField()
    _class = models.ForeignKey(Class,null = True,on_delete=models.SET_NULL)
    subjects = models.ManyToManyField(Subject,blank = True)
    classaverage = models.FloatField(blank =  True,null = True)
    classposition = models.IntegerField(blank = True,null = True)
    status = models.BooleanField(default=True)
    def __str__(self):
        return self.firstname +' '+self.lastname

class Schedule(models.Model):
    teacher = models.ForeignKey(Staff,on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    _class = models.ForeignKey(Class,on_delete=models.SET_NULL,null = True,blank = True)
    date = models.DateField()
    time = models.TimeField()

    def __str__(self):
        return self.teacher.firstname +' '+self.teacher.lastname

class Event(models.Model):
    name = models.CharField(max_length = 50)
    description = models.TextField(max_length=1500)
    date = models.DateField()
    time = models.TimeField()
    # session = models.CharField(max_length = 20)

    def __str__(self):
        return self.name
    
class EventImage(models.Model):
    event = models.ForeignKey(Event,on_delete=models.CASCADE)
    image = models.ImageField(upload_to = 'event-images')

    def __str__(self):
        return self.event.name

class Mail(models.Model):
    flag_choices = (('u','URGENT'),('i','INFO'))
    _from = models.ForeignKey(User,on_delete=models.SET_NULL,blank = True,null = True,related_name="_from")
    to = models.ForeignKey(User,blank = True,null = True,on_delete = models.SET("deleted user"))
    subject = models.CharField(max_length=100)
    message = models.TextField(max_length = 1500)
    attachment = models.FileField(upload_to = 'mail',blank = True)
    read = models.BooleanField(default = False)
    flag = models.CharField(max_length=2,choices = flag_choices)
    date = models.DateField(auto_now_add = True)
    time = models.TimeField(auto_now_add = True)

    def __str__(self):
        return self.subject

class SiteSetting(models.Model):
    name = models.CharField(max_length=20)
    value = models.CharField(max_length=50)

    def __str__(self):
        return self.name

staff/models.py
from django.db import models

# Create your models here.

staff/forms.py
from django import forms
from django.forms import ValidationError
from admins.models import Schedule, Staff,phone_validator

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        # fields = '__all__'
        exclude = ['teacher']
        widgets = {
            '_class':forms.Select(attrs={'class':'form-control'})
        }

class UploadForm(forms.Form):
    message = forms.CharField(max_length=50)
    category = forms.ChoiceField()
    file = forms.FileField()
class EditProfileForm(forms.ModelForm):
    phonenumber = forms.CharField(validators=[phone_validator])
    class Meta:
        model = Staff
        exclude = ['programme','status','position','user','phonenumber',"staff_type"]

staff/templates/Staff/base.html
{% load staticfiles %}
{% load path_checker %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.0/css/bootstrap.min.css" integrity="sha512-NZ19NrT58XPK5sXqXnnvtf9T5kLXSzGQlVZL9taZWeTBtXoN3xIfTdxbkQh6QSoJfJgpojRqMfhyqBAAEeiXcA==" crossorigin="anonymous" referrerpolicy="no-referrer" /> -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
      integrity="sha512-xX2rYBFJSj86W54Fyv1de80DWBq7zYLn2z0I9bIhQG+rxIF6XVJUpdGnsNHWRa6AvP89vtFupEPDP8eZAtu9qA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="{% static 'staff/apis/smart.default.css' %}" />
    <link rel="stylesheet" href="{% static 'staff/variables.css' %}" />
    <link rel="stylesheet" href="{% static 'staff/style.css' %}" />
    <title>{% block title %}Dashboard{% endblock %}</title>
  </head>
  <body>
    <div class="wrapper">
      <div class="sidebar">
        <h2 class="sidenav-header">Staff</h2>
        <ul class="nav-list">
          <li>
            <a href="{% url 'staff:dashboard' %}" class="nav-link"
              ><span class="nav-icon"><i class="fa-solid fa-house"></i></span
              ><span class="nav-text">Home</span></a
            >
          </li>
          <li>
            <a href="{% url 'staff:dashboard' %}" class="nav-link {% if request.path|pathcheck:'/staff/dashboard/' %}nav-active{% endif %}"
              ><span class="nav-icon"><i class="fa-solid fa-dashboard"></i></span
              ><span class="nav-text">Dashboard</span></a
            >
          </li>
          <li>
            <a href="{% url 'staff:class' %}" class="nav-link {% if request.path|pathcheck:'/staff/classes/' %}nav-active{% endif %}"
              ><span class="nav-icon"><i class="fa-solid fa-landmark"></i></span
              ><span class="nav-text">Class</span></a
            >
          </li>
          <li>
            <a href="{% url 'staff:student-list' %}" class="nav-link {% if request.path|pathcheck:'/staff/students/' %}nav-active{% endif %}"
              ><span class="nav-icon"><i class="fa-solid fa-users"></i></span
              ><span class="nav-text">Students</span></a
            >
          </li>
          <li>
            <a href="{% url 'staff:inbox-list' %}" class="nav-link {% if request.path|pathcheck:'/staff/inbox/' %}nav-active{% endif %}"
              ><span class="nav-icon"><i class="fa-solid fa-envelope"></i></span
              ><span class="nav-text">Inbox</span></a
            >
          </li>
          <li>
            <a href="{% url 'staff:uploads' %}" class="nav-link {% if request.path|pathcheck:'/staff/uploads/' %}nav-active{% endif %}"
              ><span class="nav-icon"
                ><i class="fa-solid fa-upload"></i></span
              ><span class="nav-text">Uploads</span></a
            >
          </li>
          <li>
            <a href="#" id="logout-open" class="nav-link"
              ><span class="nav-icon"><i class="fa-solid fa-sign-out"></i></span
              ><span class="nav-text">Sign Out</span></a
            >
          </li>
        </ul>
      </div>
      
      <div class="content">
        {% for message in messages %}
        <div class="flex-center pt-3 pb-3"  style="position: absolute; z-index: 1000;">
        <div class="alert alert-{{message.tags}} text-center" style=" max-width: 300px; margin: auto;" role="alert" id="liveAlert">
          {{message}}  
        </div>
      </div>
      {% endfor %}
          {% block content %}
          
          {% endblock %}
      </div>
    </div>
    <div class="modal-box hidden" id="logout-modal">
        
        <div class="form-box">
            <h3 class="header">Are you Sure?</h3>
            <div class="logout-box">
                <div class="form-group flex-between ">
                    <a href="{% url 'staff:logout' %}" class="site-button">Logout</a>
                    <a href="javascript::void(0)"  id="logout-close" class="site-button site-button-invert">Cancel</a>
                </div>
            </div>
               
                
            
        </div>
    </div>
    <!-- <script
      src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.min.js"
      integrity="sha512-EKWWs1ZcA2ZY9lbLISPz8aGR2+L7JVYqBAYTq5AXgBkSjRSuQEGqWx8R1zAX16KdXPaCjOCaKE8MCpU0wcHlHA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script> -->
    <script src="{% static 'staff/jquery.js' %}"></script>
    <script type="module" src="{% static 'staff/apis/smart.calendar.js' %}"></script>
    <script src="{% static 'staff/script.js' %}">
      
    </script>
    <script src="{% static 'staff/ajax.js' %}"></script>
    {% block extrascript %}
    {% endblock %}   
  </body>
</html>

staff/templates/Staff/inbox-details.html
{% extends 'staff/base.html' %}
{% load staticfiles %}
{% load path_checker %}
{% block title %}Message Detail{% endblock %}
{% block content %}

        <div class="pad-container flex min-h-100 flex-column">
            <div class=" pt-3 pb-3">
                <a href="{% url 'staff:inbox-list' %}" class="back-button large-text">
                    <i class="fa-solid fa-arrow-left"></i>
                </a>
                
            </div>
            <div class="box">
                <header class="flex-end">
                    <a href="{% url 'staff:inbox-delete' object.id %}" class="site-button">
                        <i class="fa-solid fa-trash"></i>&nbsp;Delete
                    </a>
                </header>
                <h3>{{object.subject}} </h3>
                <p class="small-text color-gray">
                    from: {{object|get:"_from"}}
                </p>
                <p class="pt-1 pb-1">
                    {{object.message }}
                </p>
                {% if object.attachment %}
                <a href="{{object.attachment.url}}" class="attachment">
                    {{object.attachment.name}}
                </a>
                {% endif %}
                <footer class="flex-between">
                    <span class="message color-{{object.get_flag_display}}"><i class="fa fa-bookmark"></i>&nbsp;Treat as {{object.get_flag_display}}</span>
                    <span>
                        <span><i class="fa-solid fa-clock"></i> {{ object.time }}</span>&nbsp;&nbsp;
                        <span><i class="fa-solid fa-calendar-days"></i> {{ object.date }}</span>
                    </span>
                </footer>
            </div>
        </div>
{% endblock %}

staff/templates/Staff/inbox.html
{% extends 'staff/base.html' %}
{% load staticfiles %}
{% block title %}Your Mails{% endblock %}
{% block content %}
        <div class="pad-container">
            <h2 class="header">
                Your Inbox
            </h2>
            
            <div class="boot-row row-reverse">
                
                <div class="col-md-8">
                    {% for object in page_obj %}
                    <div class="box mail-box {% if not object.read %}unread{% endif%}">
                        <h3><a href="{% url 'staff:inbox-details' object.id %}" class="link">{{object.subject}}</a></h3>
                        <p>{{object.message|truncatechars:20}}</p>
                        <span class="status-icon color-{{object.get_flag_display}}"><i class="fa-solid fa-bookmark"></i></span>
                        <footer class="flex-end small-text">
                            <span><i class="fa-solid fa-clock"></i> {{object.time}}</span>&nbsp;&nbsp;
                            <span><i class="fa-solid fa-calendar-days"></i>{{object.date}}</span>
                        </footer>
                    </div>
                    {% empty %}
                    <div class="no-item">
                        <p>No Mail</p>
                    </div>
                    {% endfor %}
                    {% if page_obj %}
                    <div class="flex-center">
                        <ul class="paginator">
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" ><span>&laquo;</span></a></li>
                                <li class="page-item">
                                    <a class="page-link" href="?page={{page_obj.previous_page_number}}">{{page_obj.previous_page_number}}</a>
                                </li>
                                {% else %}
                                <li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true"><span>&laquo;</span></a></li>
                            {% endif %}
                            
                            {% for pagenum in page_obj.paginator.page_range %}
                            {% if page_obj.number == pagenum %}
                                <li class="page-item{% if page_obj.number == pagenum %} active{% endif %}">
                                    <a class="page-link" href="?page={{pagenum}}">{{pagenum}}</a>
                                </li>
                            {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link" href="?}page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}"><span>&raquo;</span></a></li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link" href="#" ><span>&raquo;</span></a></li>
                            {% endif %}
                        </ul>
                    </div>
                    {% endif %}
                </div>
                <div class="col-md-4 mb-4">
                    <div class="flex-center">
                        <smart-calendar id="calander"></smart-calendar>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

staff/templates/Staff/profile.html
{% extends 'staff/base.html' %}
{% load staticfiles %}
{% block title %} Your Profile {% endblock %}
{% block content %}
            <div class="pad-container pt-4">
                <div>
                    <a href="{% url 'staff:dashboard' %}" class="back-button large-text">
                        <i class="fa-solid fa-arrow-left"></i>
                    </a>
                    
                </div>
                <h2 class="header flex-between">
                    Your Information
                    <a href="{% url 'staff:change-password'%}" class="site-button small-text"><i class="fa-solid fa-lock"></i> Change Password</a>
                </h2>
                <div class="row-6">
                    <div class="column-6">
                        <div class="box">
                            <h3 class="flex-between">Personal Information <a href="{% url 'staff:edit-profile'%}" class="site-button small-text"><i class="fa fa-pencil"></i>&nbsp; Edit</a></h3>
                           {% if data.image %}
                                <img src="{{ data.image.url}}" class="detail-profile-image">
                            {% else %}
                            {% if data.sex == 'M'%}
                                <img src="{% static 'staff/images/male-placeholder.png' %}" class="detail-profile-image">
                            {% else %}
                                <img src="{% static 'staff/images/female-placeholder.png' %}" class="detail-profile-image">
                            {% endif %}
                            {% endif %}

                            <ul class="detail-content line-height-small">
                                <li><strong>Name of Staff:</strong> {{data.firstname}} {{data.lastname}}</li>
                                <li><strong>Date of Birth:</strong> {{data.dob}}</li>
                                <li><strong>Sex:</strong> {{data.get_sex_display}}</li>
                                <li><strong>Phone Number:</strong> {{data.phonenumber}}</li>
                                <li><strong>Email:</strong> {{request.user.email}}</li>
                                <li><strong>State:</strong> {{data.state}} </li>
                                <li><strong>Local Government:</strong> {{data.lga}}</li>
                                <li><strong>Home Town:</strong> {{data.hometown}}</li>
                                <!-- <li><strong>Residential Address:</strong> Omorinre Johnson Street, Lekki Phase 1,Lagos</li> -->
                                <li><strong>Account Number:</strong> {{data.accountnumber|default:"Not Provided"}}</li>
                                <li><strong>Account Name:</strong> {{data.accountname|default:"Not Provided"}}</li>
                                <li><strong>Bank:</strong> {{data.bank|default:"Not Provided"}}</li>
                            </ul>
                        </div>
                    </div>
                    <div class="column-6">
                        <div class="box">
                            <h3>School Information</h3>
                            <ul class="detail-content line-height-small">
                                <li><strong>Your Class(es):</strong> <ul class="inner-list">
                                    {% for x in classes %}
                                    <li>{{x}}</li>
                                    {% empty %}
                                    <div class="no-item">
                                        <p>
                                            None Assigned
                                        </p>
                                    </div>
                                    {% endfor %}

                                </ul></li>
                                <li><strong> Your Subject(s):</strong><ul class="inner-list">
                                    {% for x in subjects %}
                                    <li>{{x}}</li>
                                    {% empty %}
                                    <div class="no-item">
                                        <p>
                                            None Assigned
                                        </p>
                                    </div>
                                    {% endfor %}
                                </ul></li>
                                <li><strong>Position: </strong> {{data.position|default:"None assigned"}} </li>
                                <li><strong>Status: </strong> <span class="color-success">{{data.status}}</span> </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}

staff/templates/Staff/student-details.html
{% extends 'staff/base.html' %}
{% load staticfiles %}
{% load path_checker %}
{% block title %}{{object.firstname}} {{object.lastname}} | Student{% endblock %}
{% block content %}
            <div class="pad-container pt-4">
                <div>
                    <a href="{% url 'staff:student-list' %}" class="back-button large-text">
                        <i class="fa-solid fa-arrow-left"></i>
                    </a>   
                </div>
                <h2 class="header">
                    Student Information
                </h2>
                <div class="row-6">
                    <div class="column-6">
                        <div class="box">
                            <h3>Personal Information</h3>
                           {% if object.image %}
                                    <img src="{{ object.image.url}}"  class="detail-profile-image" >
                                {% else %}
                                {% if object.sex == 'M'%}
                                    <img src="{% static 'staff/images/male-placeholder.png' %}"  class="detail-profile-image">
                                {% else %}
                                    <img src="{% static 'staff/images/female-placeholder.png' %}"  class="detail-profile-image">
                                {% endif %}
                            {% endif %}
                            <ul class="detail-content line-height-small">
                                <li><strong>Name of Student:</strong> {{object.firstname}} {{object.lastname}}</li>
                                <li><strong>Date of Birth:</strong> {{object.dob}}</li>
                                <li><strong>Sex:</strong> {{object.get_sex_display}}</li>
                                <!-- <li><strong>Nationality: </strong>Nigerian</li> -->
                                <li><strong>State:</strong> {{object.state}} </li>
                                <li><strong>Local Government:</strong> {{object.lga}}</li>
                                <li><strong>Home Town:</strong> {{object.hometown}}</li>
                                <!-- <li><strong>Residential Address:</strong> Omorinre Johnson Street, Lekki Phase 1,Lagos</li> -->
                                <li><strong>Guardian Name:</strong> {{object.guardianname}}</li>
                                <!-- <li><strong>Guardian Phone Number:</strong> 09018782256</li> -->
                            </ul>
                        </div>
                    </div>
                    <div class="column-6">
                        <div class="box">
                            <h3>School Information</h3>
                            <ul class="detail-content line-height-small">
                                <li><strong>Class:</strong> {{object|get:"_class"}}</li>
                                <li><strong>Subject Offered:</strong><ul class="inner-list">
                                    {% for x in object.subjects.all %}
                                    <li>{{x}}</li>
                                    {% endfor %}
                                </ul></li>
                                <!-- <li><strong>Average: </strong>76.5</li>
                                <li><strong>Position: </strong>10th </li> -->
                                <li><strong>Status: </strong> <span class="color-success">{%if object.status %}active{% else %}inactive{% endif %}</span> </li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
{% endblock %}