admins/urls.py
from django.urls import path
from .views import *

app_name = 'admins'

urlpatterns = [
    path('',home),
    path('dashboard/',DashboardView.as_view(),name='dashboard'),
    path('staff/',StaffListView.as_view(),name="staff"),
    path('staff/add/',StaffAddFormView.as_view(),name="staff-add"),
    path('staff/<int:pk>/',StaffDetailView.as_view(),name="staff-details"),
    path('staff/<int:id>/get-schedule/',scheduleGetView),
    path('staff/<int:id>/toggle-status/',StaffStatusToggle.as_view(),name="staff-toggle"),
    path('staff/<int:id>/delete/',StaffDeleteView.as_view(),name="staff-delete"),
    path('student/',StudentListView.as_view(),name="student"),
    path('student/add/',StudentAddFormView.as_view(),name="student-add-form"),
    path('student/<int:pk>/',StudentDetailView.as_view(),name="student-details"),
    path('student/<int:id>/toggle-status/',StudentStatusToggle.as_view(),name="student-toggle"),
    path('student/<int:id>/delete/',StudentDeleteView.as_view(),name="student-delete"),
    path('mail/',InboxView.as_view(),name="inbox"),
    path('mail/received/',InboxReceivedView.as_view(),name="inbox-received"),
    path('mail/sent/',InboxSentView.as_view(),name="inbox-sent"),
    path('mail/create/',InboxFormView.as_view(),name="inbox-create"),
    path('event/',EventView.as_view(),name="event"),
    path('event/add/',EventFormView.as_view(),name="event-add"),
    path('event/<int:id>/',EventDetailsView.as_view(),name="event"),
    path('programme/',ProgrammeView.as_view(),name="programme"),
    path('programme/add-class',ProgrammeClassFormView.as_view(),name="programme-add-class"),
    path('programme/add-subject',ProgrammeSubjectFormView.as_view(),name="programme-add-subject"),
    path('programme/add-topic',ProgrammeTopicFormView.as_view(),name="programme-add-topic"),
    path('programme/class/<int:pk>/edit',ProgrammeUpdateClassView.as_view(),name="programme-edit-class"),
    path('programme/subject/<int:pk>/edit',ProgrammeUpdateSubjectView.as_view(),name="programme-edit-subject"),
    path('settings/',SettingsView.as_view(),name="settings"),
    path('settings/password',SettingsPasswordChangeView.as_view(),name="settings-password"),
    path('logout/',LogoutView.as_view(),name="logout"),
]

main/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('',indexview,name = 'index'),
    path('about/',aboutview,name = 'about'),
    path('contact-us/',contactview,name = 'contact'),
    path('news',newsview,name = 'news'),
    path('news/<int:id>/',newsdetailview,name = 'news-detail'),
    path('login/',LoginView.as_view(),name = 'login')
]

schoolportal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import main
import staff
import admins
urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('',include("main.urls")),
    path('admin/',include("admins.urls")),
    path('staff/',include("staff.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admins/templates/admins/settings/Users.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.0/css/bootstrap.min.css" integrity="sha512-NZ19NrT58XPK5sXqXnnvtf9T5kLXSzGQlVZL9taZWeTBtXoN3xIfTdxbkQh6QSoJfJgpojRqMfhyqBAAEeiXcA==" crossorigin="anonymous" referrerpolicy="no-referrer" /> -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;400&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
      integrity="sha512-xX2rYBFJSj86W54Fyv1de80DWBq7zYLn2z0I9bIhQG+rxIF6XVJUpdGnsNHWRa6AvP89vtFupEPDP8eZAtu9qA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="./fontawesome-free-5.12.1-web/css/all.min.css"
    />
    <link rel="stylesheet" href="../apis/smart.default.css" />
    <link rel="stylesheet" href="style.css" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.min.js"
      integrity="sha512-EKWWs1ZcA2ZY9lbLISPz8aGR2+L7JVYqBAYTq5AXgBkSjRSuQEGqWx8R1zAX16KdXPaCjOCaKE8MCpU0wcHlHA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <script type="module" src="../apis/smart.calendar.js"></script>
    <title>Inbox</title>
  </head>
  <body>
    <div class="wrapper">
      <div class="sidebar">
        <h2 class="sidenav-header">Admin</h2>
        <ul class="nav-list">
          <li>
            <a href="index.html" class="nav-link"
              ><span class="nav-icon"><i class="fas fa-th-large"></i></span
              ><span class="nav-text">Dashboard</span></a
            >
          </li>
          <li>
            <a href="staffs.html" class="nav-link"
              ><span class="nav-icon"><i class="fas fa-users"></i></span
              ><span class="nav-text">Staffs</span></a
            >
          </li>
          <li>
            <a href="students.html" class="nav-link"
              ><span class="nav-icon"><i class="fas fa-user-graduate"></i></span
              ><span class="nav-text">Students</span></a
            >
          </li>
          <li>
            <a href="inbox.html" class="nav-link"
              ><span class="nav-icon"><i class="fas fa-envelope"></i></span
              ><span class="nav-text">Inbox</span></a
            >
          </li>
          <li>
            <a href="events.html" class="nav-link"
              ><span class="nav-icon"><i class="fas fa-calendar-alt"></i></span
              ><span class="nav-text">Events</span></a
            >
          </li>
          <li>
            <a href="programme.html" class="nav-link"
              ><span class="nav-icon"><i class="fas fa-tasks"></i></span
              ><span class="nav-text">Programme</span></a
            >
          </li>

          <li>
            <a href="settings.html" class="nav-link nav-active"
              ><span class="nav-icon"><i class="fas fa-cog"></i></span
              ><span class="nav-text">Settings</span></a
            >
          </li>
          <li>
            <a href="javascript:void(0)" id="logout-open" class="nav-link"
              ><span class="nav-icon"><i class="fas fa-sign-out-alt"></i></span
              ><span class="nav-text">Sign Out</span></a
            >
          </li>
        </ul>
      </div>
      <div class="content">
        <div class="content-nav">
          <h2 class="greetings">Settings</h2>
          <!-- <a href="#" class="content-nav-link">
            <span class="nav-icon">
              <span class="add-event"></span>
            </span>
          </a> -->
        </div>

        <!-- content features -->
        <div class="settings-content">
          <div class="settings-wrapper">
            <ul class="settings-nav">
              <a href="settings.html" class="settings-nav-link">
                <li class="settings-nav-item">My Details</li>
              </a>

              <a href="password.html" class="settings-nav-link">
                <li class="settings-nav-item">Password</li>
              </a>
              <a href="email.html" class="settings-nav-link">
                <li class="settings-nav-item">Email</li>
              </a>
              <a href="Users.html" class="settings-nav-link nav-current">
                <li class="settings-nav-item">Users</li>
              </a>
              <a href="#" class="settings-nav-link">
                <li class="settings-nav-item">Site Info</li>
              </a>
            </ul>
          </div>
          <!-- deatails -->
          <div class="details-content">
            <!-- nav header -->
            <div class="details-nav">
              <div class="personal-info">
                <h1 class="personal-info-header">Users</h1>
                <p class="personal-info-sub-header">Select users</p>
              </div>
              <!-- nav btn -->
              <!-- <div class="nav-link-add">
                <a href="#" class="nav-icon-cancel">Cancel</a>
                <a href="#" class="nav-icon-save">Save</a>
              </div>-->
            </div>

            <!-- Notification from Admin -->
            <div class="personnel-name">
              <div class="personnel-container">
                <div class="detail-name">
                  <h1 class="detail-name-header">Add admin</h1>
                </div>

                
                
              </div>
            </div>
            <!-- reminder -->
          </div>
        </div>
      </div>
    </div>
    <script type="module" src="../apis/smart.calendar.js"></script>
    <script>
      window.onload = function () {
        Smart(
          "#calendar",
          class {
            get properties() {
              return { selectedDates: ["2020-7-2", "2020-7-17"] };
            }
          }
        );
        document.querySelector("smart-calendar").selectedDates = [
          "2018-1-1",
          new Date(2018, 0, 2),
        ];
      };
    </script>
    <div class="modal-box hidden" id="logout-modal">
      <div class="form-box">
        <h3 class="header">Are you Sure?</h3>
        <div class="logout-box">
          <div class="form-group flex-between">
            <a href="logout.html" class="site-button">Logout</a>
            <a
              href="javascript::void(0)"
              id="logout-close"
              class="site-button site-button-invert"
              >Cancel</a
            >
          </div>
        </div>
      </div>
    </div>
    <script src="sigout.js"></script>
  </body>
</html>

admins/templates/admins/settings/base.html
{% extends 'admins/base.html' %}
{% block title %}settings{% endblock %}
{% block content %}
          <h2 class="greetings">Settings</h2>
          <!-- <a href="#" class="content-nav-link">
            <span class="nav-icon">
              <span class="add-event"></span>
            </span>
          </a> -->
        <!-- content features -->
        <div class="settings-content">
          <div class="settings-wrapper">
            <ul class="settings-nav">
              <a href="{% url 'admins:settings' %}" class="settings-nav-link {% if request.path == '/admin/settings/' %}nav-current{% endif %}">
                <li class="settings-nav-item">My Details</li>
              </a>

              <a href="{% url 'admins:settings-password' %}" class="settings-nav-link {% if request.path == '/admin/settings/password/' %}nav-current{% endif %}">
                <li class="settings-nav-item">Password</li>
              </a>
              <a href="#" class="settings-nav-link">
                <li class="settings-nav-item">Email</li>
              </a>
              <a href="#" class="settings-nav-link">
                <li class="settings-nav-item">Users</li>
              </a>
              <a href="#" class="settings-nav-link">
                <li class="settings-nav-item">Site Info</li>
              </a>
            </ul>
          </div>
          <div>
              {% block settings_content %}
              {% endblock %}
          </div>
        </div>
         
{% endblock %}

admins/templates/admins/settings/change-password.html
{% extends 'admins/settings/base.html' %}
{% block settings_content %}
          <div class="details-content">
            <!-- nav header -->
            <div class="details-nav">
              <div class="personal-info">
                <h1 class="personal-info-header">Password</h1>
                <p class="personal-info-sub-header">
                  please enter your current to change your password.
                </p>
              </div>
              <form action="" method="POST">
                {% csrf_token %}
              
              <!-- nav btn -->
              <div class="nav-link-add">
                <a href="#" class="nav-icon-cancel">Cancel</a>
                <input type="submit" value="Update" class="nav-icon-save">
              </div>
            </div>

            <!-- current password -->
            <div class="personnel-name">
              <div class="personnel-container">
                <div class="detail-name">
                  <h1 class="detail-name-header">Current Password</h1>
                </div>

                <!-- input fields -->

                <input
                  type="password"
                  name="old_password"
                  placeholder="Current Password"
                  class="input-four"
                />
               
              </div>
              <span class="error-msg">{{form.old_password.errors|default:''}}</span>
            </div>
          </div>
          <!-- New password -->
          <div class="personnel-email">
            <div class="email-container">
              <div class="detail-email">
                <h1 class="detail-name-header">New Password</h1>
              </div>

              <!-- input fields -->
              <div class="detail-email-input">
                <input
                  type="password"
                  name="new_password1"
                  placeholder="New Password"
                  class="input-two"
                />
                <!-- message -->
                <p class="password-message">
                  password must be more than 8 characters
                </p>
              <span class="error-msg">{{form.new_password1.errors|default:''}}</span>
              </div>
            </div>
          </div>

          <!-- confirm password -->
          <div class="personnel-role">
            <div class="role-container">
              <div class="detail-name">
                <h1 class="detail-name-header">Confirm Password</h1>
              </div>

              <!-- input fields -->
              <div class="detail-role-input">
                <input
                  type="password"
                  name="new_password2"
                  placeholder="Confirm Password"
                  class="input-two"
                />
              </div>
            </div>
            <span class="error-msg">{{form.new_password2.errors|default:''}}</span>
          </div>
        </form>
{% endblock %}

admins/templates/admins/settings/settings.html
{% extends 'admins/settings/base.html' %}
{% block settings_content %}
          <div class="details-content">
            <!-- nav header -->
            <div class="details-nav">
              <div class="personal-info">
                <h1 class="personal-info-header">Personal Info</h1>
                <p class="personal-info-sub-header">
                  Update your photo and personal details here.
                </p>
              </div>
              <!-- nav btn -->
              <div class="nav-link-add">
                <a href="#" class="nav-icon-cancel">Cancel</a>
                <a href="#" class="nav-icon-save">Save</a>
              </div>
            </div>

            <!-- name -->
            <div class="personnel-name">
              <div class="personnel-container">
                <div class="detail-name">
                  <h1 class="detail-name-header">Name</h1>
                </div>

                <!-- input fields -->
                <div class="detail-name-input">
                  <input
                    type="text"
                    name="surname"
                    id="surname"
                    placeholder="surname"
                    class="input-one"
                  />
                  <input
                    type="text"
                    name="firstname"
                    id="firstname"
                    placeholder="firstname"
                    class="input-one"
                  />
                </div>
              </div>
            </div>
            <!-- email -->
            <div class="personnel-email">
              <div class="email-container">
                <div class="detail-email">
                  <h1 class="detail-name-header">Email</h1>
                </div>

                <!-- input fields -->
                <div class="detail-email-input">
                  <input
                    type="email"
                    name="email"
                    id="email"
                    placeholder="email"
                    class="input-two"
                  />
                </div>
              </div>
            </div>
            <!-- role -->
            <div class="personnel-role">
              <div class="role-container">
                <div class="detail-name">
                  <h1 class="detail-name-header">Role</h1>
                </div>

                <!-- input fields -->
                <div class="detail-role-input">
                  <input
                    type="text"
                    name="role"
                    id="role"
                    placeholder="role"
                    class="input-two"
                  />
                </div>
              </div>
            </div>
            <!-- Photo-->
            <div class="personnel-email">
              <div class="email-container">
                <div class="detail-email">
                  <h1 class="detail-name-header">Photo</h1>
                  <p class="personal-info-sub-header photo-info">
                    This would be displayed on your profile
                  </p>
                </div>

                <!-- input fields -->
                <div class="admin-profile-icon">
                  <img
                    src="./images/pexels-tuấn-kiệt-jr-1382731.jpg"
                    class="detail-profile-image admin-img"
                  />
                  <input type="file" name="" id="" class="input-three" />
                </div>
              </div>
            </div>

            <!-- Photo-->
            <div class="personnel-email">
              <div class="email-container">
                <div class="detail-email">
                  <h1 class="detail-name-header">Company Logo</h1>
                  <p class="personal-info-sub-header photo-info">
                    Upload your company logo.
                  </p>
                </div>

                <!-- input fields -->
                <div class="admin-profile-icon">
                  <img
                    src="./images/144-1443138_mac-maple-grove-school-islamic-school-logo-design.png"
                    class="detail-profile-image admin-img"
                  />
                  <input type="file" name="" id="" class="input-three" />
                </div>
              </div>
            </div>
          </div>
{% endblock %}